server:
  port: 8484
  error: #제 register가 작동을 안해서 추가했는데 오히려 자기쪽에서 안되면 다시 지워주세요
    include-message: always

spring:
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 3s
  mail:
    host: smtp.gmail.com
    port: 587
    username: kh085748@gmail.com # 본인의 Gmail 주소
    password: srwkbjvlmiulwxnx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/atom?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: bts
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 585229264354-efrgpbcu42oc0t9sm4rtvqdop5m38cuu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: 5a84ef1383c8de0e2864ac787ba900b5
            client-secret: 3Ako7HeoSGQEMhuCHwWk2r2lXOZ9Cb16
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8484/login/oauth2/code/kakao
            scope:
              - profile_nickname
            client-name: Kakao
          naver:
            client-id: Piz3iuubAjIvywGXQCV0
            client-secret: T9v_xdT62F
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8484/login/oauth2/code/naver
            scope:
              - name
              - email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  tmdb:
    api-key: 3d3fea3abfd1ffa8c4b49dc551ddc494
    base-url: https://api.themoviedb.org/3
openai:
  api-key: ${OPENAI_API_KEY}

jwt:
  secret-key: WonderfulSecretKeyForJWTSigningAndParsingWithHMACSHA256
  expiration-time: 3600000 # 토큰 만료 시간 (1시간 = 3600000ms)
toss:
  payments:
    secret:
      key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R
